version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    container_name: task_server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    env_file: ./server/.env.dev
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  data-volume:
