
export enum CATAGORY_NAME {
  "COMMERCIAL_AUTO" = "COMMERCIAL_AUTO",
  "PERSONAL_AUTO" = "PERSONAL_AUTO",
  "HOME_OWNERS" = "HOME_OWNERS",
  "BUSINESS_OWNERS" = "BUSINESS_OWNERS",
  "COMMERCIAL_PACKAGE" = "COMMERCIAL_PACKAGE",
  "WORKERS_COMPENSATION" = "WORKERS_COMPENSATION",
  "GENERAL_LIABILITY" = "GENERAL_LIABILITY",
  "PERSONAL_UMBRELLA" = "PERSONAL_UMBRELLA",
  "BOND" = "BOND",
  "COMMERCIAL_INLAND_MARINE" = "COMMERCIAL_INLAND_MARINE",
  "ERROR_AND_OMISSIONS" = "ERROR_AND_OMISSIONS",
  "EXCESS_LIABILITY" = "EXCESS_LIABILITY",
  "FLOOD_PERSONAL" = "FLOOD_PERSONAL",
  "CONDO" = "CONDO",
  "DWELLING_FIRE" = "DWELLING_FIRE",
  "RENTERS" = "RENTERS",
}