
export enum CATAGORY_NAME {
  "COMMERCIAL_AUTO" = "COMMERCIAL_AUTO",
  "COMMERCIAL_PACKAGE" = "COMMERCIAL_PACKAGE",
  "COMMERCIAL_INLAND_MARINE" = "COMMERCIAL_INLAND_MARINE",
  "COMMERCIAL_PROPERTY" = "COMMERCIAL_PROPERTY",
  "COMMERCIAL_UMBRELLA" = "COMMERCIAL_UMBRELLA",

  "PERSONAL_AUTO" = "PERSONAL_AUTO",
  "PERSONAL_UMBRELLA" = "PERSONAL_UMBRELLA",
  "HOME_OWNERS" = "HOME_OWNERS",
  "BUSINESS_OWNERS" = "BUSINESS_OWNERS",
  "RENTERS" = "RENTERS",
  "WORKERS_COMPENSATION" = "WORKERS_COMPENSATION",
  "GENERAL_LIABILITY" = "GENERAL_LIABILITY",
  "BOND" = "BOND",
  "ERRORS_AND_OMISSIONS" = "ERRORS_AND_OMISSIONS",
  "EXCESS_LIABILITY" = "EXCESS_LIABILITY",
  "FLOOD_PERSONAL" = "FLOOD_PERSONAL",
  "CONDO" = "CONDO",
  "DWELLING_FIRE" = "DWELLING_FIRE",
  "WATERCRAFT_SMALL_BOAT" = "WATERCRAFT_SMALL_BOAT"
}