# FROM node:lts-alpine
FROM phusion/passenger-nodejs

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json . 
COPY package-lock.json .

RUN npm -g install npm@^6.11.0 
RUN npm i -g @nestjs/cli
RUN npm install

COPY . .

EXPOSE 8000

CMD [ "npm", "run", "start:dev"]